spring.application.name= store-inventory-manager-v1

# Configuracion de MyBatis
mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mappers/**/*.xml

server.port=9090



server.error.include-message=always
server.error.include-binding-errors=always
server.error.whitelabel.enabled=false


server.servlet.context-path=/api

security.jwt.user.generator=AUTH0JWT-BACKEND
security.jwt.token.expiration=1800000



base.url.openFoodFacts= https://world.openfoodfacts.org/

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.sdh.store.inventory.manager=DEBUG
logging.level.org.springframework.core.env=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.profiles.active=local
