spring.application.name= store-inventory-manager-v1
spring.datasource.url=jdbc:postgresql://localhost:5432/store_senor_de_huanca
spring.datasource.username=postgres
spring.datasource.password=20051996
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=sdh.store.inventory.manager.model

server.port=9090

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE