#Configuracion de la base de datos local
spring.datasource.url=jdbc:postgresql://localhost:5432/store_senor_de_huanca
spring.datasource.username=postgres
spring.datasource.password=20051996

#Configuracion JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#Clave privada JWT (se debe usar una variable de entorno seguro)
security.jwt.key.private=2dd57dfe27e671d7fad1d9517900518607dfb1d0a4718105b2e69986349d0a83

# Security Config
spring.security.user.name=sleyther
spring.security.user.password=1234
