spring.application.name= store-inventory-manager-v1
spring.datasource.url=jdbc:postgresql://localhost:5432/store_senor_de_huanca
spring.datasource.username=postgres
spring.datasource.password=20051996
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

mybatis.config-location=classpath:mybatis-config.xml
mybatis.mapper-locations=classpath:mappers/**/*.xml
#mybatis.type-aliases-package=sdh.store.inventory.manager
#mybatis.configuration.map-underscore-to-camel-case=true

server.port=9090

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


server.error.include-message=always
server.error.include-binding-errors=always
server.error.whitelabel.enabled=false


server.servlet.context-path=/api

security.jwt.key.private=2dd57dfe27e671d7fad1d9517900518607dfb1d0a4718105b2e69986349d0a83
security.jwt.user.generator=AUTH0JWT-BACKEND
security.jwt.token.expiration=1800000

# Security Config
spring.security.user.name=sleyther
spring.security.user.password=1234


base.url.openFoodFacts= https://world.openfoodfacts.org/

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.sdh.store.inventory.manager=DEBUG
logging.level.org.springframework.core.env=DEBUG